name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Install dependencies
      run: dotnet restore "./Resolve 3D/Resolve3D.Tests/Resolve3D.Tests.csproj"

    - name: Build solution
      run: dotnet build "./Resolve 3D/Resolve3D.Tests/Resolve3D.Tests.csproj" --configuration Release

    - name: Run tests and generate JUnit report
      run: dotnet test "./Resolve 3D/Resolve3D.Tests/Resolve3D.Tests.csproj" --logger "junit;LogFileName=test-results.xml"

    - name: Upload Test Results
      uses: actions/upload-test-results@v1
      with:
        format: junit
        path: './Resolve 3D/Resolve3D.Tests/TestResults/test-results.xml'
